# The basic colors
foreground              #000000
background              #EEEEEE
selection_foreground    #000000
selection_background    #AFD7FF

# Cursor colors
cursor                  #000000
cursor_text_color       #EEEEEE

# kitty window border colors
active_border_color     #193668
inactive_border_color   #9f9f9f

# Tab bar colors
active_tab_foreground   #005fd7
active_tab_background   #EEEEEE
inactive_tab_foreground #EEEEEE
inactive_tab_background #A6A6A6
tab_bar_background      #D9D9D9

# The basic 16 colors
# black
color0 #000000
color8 #585858

# red
color1 #D70000
color9 #D70000

# green
color2  #005F00
color10 #005F00

# yellow
color3  #D75F00
color11 #D75F00

# blue
color4  #005FD7
color12 #005FD7

# magenta
color5  #5F00D7
color13 #5F00D7

# cyan
color6  #0087AF
color14 #0087AF

# white
color7  #B2B2B2
color15 #B2B2B2
