background  #012456
foreground  #CCCCCC
selection_foreground  #012456
selection_background  #ffffff

cursor                #ffffff

# Tab bar colors
active_tab_foreground   #012456
active_tab_background   #FFFFFF
inactive_tab_background #012456
inactive_tab_foreground #CCCCCC
tab_bar_background      #012456

color0        #0C0C0C
color8        #767676
color1        #C50F1F
color9        #E74856
color2        #13A10E
color10       #16C60C
color3        #C19C00
color11       #F9F1A5
color4        #0037DA
color12       #3B78FF
color5        #881798
color13       #B4009E
color6        #3A96DD
color14       #61D6D6
color7        #CCCCCC
color15       #F2F2F2
